### ISSUE TITLE
How is final ycm_core.cpython-XXX-x86_64-linux-gnu.so name determined ?

### ISSUE THREAD

**Issue by Halfwalker** [ycm-core/ycmd#1660]
Not really an issue ...  Trying to figure out how the final .so filename is determined from the existing python3 installation.

For example, on an Ubuntu 18.04 box with python 3.6.9 it produces
```
ycm_core.cpython-36m-x86_64-linux-gnu.so
```
while on an Ubuntu 22.04 with python 3.10.4 it produces
```
ycm_core.cpython-310-x86_64-linux-gnu.so
```
Why wasn't the **36m** one actually **364** ?  Trying to find a deterministic way to know the filename in advance.  This is all to aid an ansible role that builds it as part of installing the YouCompleteMe vim plugin - the task is like
```
  - name: Build ycmd for YouCompleteMe
    command: "python3 install.py --force-sudo {{ vim_clang_completer }}"
    args:
      chdir: "/home/{{ username }}/.vim/bundle/YouCompleteMe"
      creates: "/home/{{ username }}/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.cpython-310-x86_64-linux-gnu.so"
```
but need a way to parameterize the **310** that's in the **creates:** line
